name = "VaidyaPT"
uuid = "06765c70-09de-4204-b8a5-13d5fad5fa47"
authors = ["Jaime <jaime.redondo.yuste@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
